modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="worlddriver-common.mixins.json"

[[mods]]
modId="worlddriver"
version="${version}"
displayName="WorldDriver"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.worlddriver]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.worlddriver]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.worlddriver]]
    modId="architectury"
    type="required"
    versionRange="${architectury_version_range}"
    ordering="AFTER"
    side="BOTH"
